import type { Metadata } from "next";
import "@/app/globals.css";
import i18nConfig from "./i18nConfig";

export const metadata: Metadata = {
  title: "Master Pics",
  description: "Generated by create next app",
};

export function generateStaticParams(){
  return i18nConfig.locales.map((locale) => ({locale}))
}

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string}
}>) {
  return (
    <html lang={locale}>
      <body>
        {children}
      </body>
    </html>
  );
}
